# Generated by Django 4.1.7 on 2023-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendinglimit',
            name='dateLimit',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
